<a href="https://colab.research.google.com/github/geethango/baseline_model/blob/main/beseline_model_difference.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
scaler = StandardScaler()

## **`MATCHUP DATA REGULAR SEASON 2011_12 `**

In [3]:
path=r'/content/drive/MyDrive/data collection/FINAL MODEL FEEDING DATASET (V - H) direct difference/FINAL_2011_12_MODEL_FEEDING_DATASET_ATTEMPTED_BY_DIFFERENCE.csv'
data_2011_12=pd.read_csv(path)
data_2011_12 = data_2011_12.loc[~data_2011_12.index.duplicated(keep='first')]
data_2011_12.drop(["Unnamed: 0",'Visitor','Home','E+/-'],axis = 1, inplace  = True)
data_2011_12.head()
count = 0
for i in range(0,data_2011_12.shape[0]) :
    if data_2011_12.loc[i].isnull().sum() > 0 :
        count = count + 1
        print(f'Number of null values in row {i} : ' + str(data_2011_12.loc[i].isnull().sum()))
        
count
data_2011_12.columns

Index(['G', 'G.1', 'Total_goal', 'Rk', 'AvAge', 'GP', 'W', 'L', 'OL', 'PTS',
       'PTS%', 'GF', 'GA', 'SOW', 'SOL', 'SRS', 'SOS', 'GF/G', 'GF/G.1', 'PP',
       'PPO', 'PP%', 'PPA', 'PPOA', 'PK%', 'SH', 'SHA', 'PIM/G', 'oPIM/G', 'S',
       'S%', 'SA', 'SV%', 'SO', 'Rk.1', 'Age', 'GP.1', 'CF', 'CA', 'CF%',
       'CF% rel', 'FF', 'FA', 'FF%', 'FF rel', 'oiSH%', 'oiSV%', 'PDO', 'oZS%',
       'dZS%', 'TK', 'GV', 'SAtt', 'Thru%', 'Rk.2', 'Age.1', 'GP.2', 'G.1.1',
       'A', 'PTS.1', '+/-', 'PIM', 'PS', 'EV', 'PP.1', 'SH.1', 'GW',
       'Assist-EV', 'PP.2', 'Assist-SH', 'S.1', 'S%.1', 'TOI', 'BLK', 'HIT',
       'FOW', 'FOL', 'FO%'],
      dtype='object')

In [4]:
data_2011_12.isna().any()
data_2011_12.columns[data_2011_12.isna().any()].tolist()

[]

:## **`MATCHUP DATA REGULAR SEASON 2012_13 `**

In [5]:
path=r'/content/drive/MyDrive/data collection/FINAL MODEL FEEDING DATASET (V - H) direct difference/FINAL_2012_13_MODEL_FEEDING_DATASET_ATTEMPTED_BY_DIFFERENCE.csv'
data_2012_13=pd.read_csv(path)
data_2012_13.drop(["Unnamed: 0",'Visitor','Home',],axis = 1, inplace  = True)
data_2012_13 = data_2012_13.loc[~data_2012_13.index.duplicated(keep='first')]
data_2012_13.head()
count = 0
for i in range(0,data_2012_13.shape[0]) :
    if data_2012_13.loc[i].isnull().sum() > 0 :
        count = count + 1
        print(f'Number of null values in row {i} : ' + str(data_2012_13.loc[i].isnull().sum()))
        
count
data_2012_13.columns

Index(['G', 'G.1', 'Total_goal', 'Rk', 'AvAge', 'GP', 'W', 'L', 'OL', 'PTS',
       'PTS%', 'GF', 'GA', 'SOW', 'SOL', 'SRS', 'SOS', 'GF/G', 'GF/G.1', 'PP',
       'PPO', 'PP%', 'PPA', 'PPOA', 'PK%', 'SH', 'SHA', 'PIM/G', 'oPIM/G', 'S',
       'S%', 'SA', 'SV%', 'SO', 'Rk.1', 'Age', 'GP.1', 'CF', 'CA', 'CF%',
       'CF% rel', 'FF', 'FA', 'FF%', 'FF rel', 'oiSH%', 'oiSV%', 'PDO', 'oZS%',
       'dZS%', 'TK', 'GV', 'SAtt', 'Thru%', 'Rk.2', 'Age.1', 'GP.2', 'G.1.1',
       'A', 'PTS.1', '+/-', 'PIM', 'PS', 'EV', 'PP.1', 'SH.1', 'GW',
       'Assist-EV', 'PP.2', 'Assist-SH', 'S.1', 'S%.1', 'TOI', 'BLK', 'HIT',
       'FOW', 'FOL', 'FO%'],
      dtype='object')

## **`MATCHUP DATA REGULAR SEASON 2013_14 `**

In [6]:
path=r'/content/drive/MyDrive/data collection/FINAL MODEL FEEDING DATASET (V - H) direct difference/FINAL_2013_14_MODEL_FEEDING_DATASET_ATTEMPTED_BY_DIFFERENCE.csv'
data_2013_14=pd.read_csv(path)
data_2013_14.drop(["Unnamed: 0",'Visitor','Home','E+/-'],axis = 1, inplace  = True)
data_2013_14 = data_2013_14.loc[~data_2013_14.index.duplicated(keep='first')]
data_2013_14.head()
count = 0
for i in range(0,data_2013_14.shape[0]) :
    if data_2013_14.loc[i].isnull().sum() > 0 :
        count = count + 1
        print(f'Number of null values in row {i} : ' + str(data_2013_14.loc[i].isnull().sum()))
        
count
data_2013_14.columns

Index(['G', 'G.1', 'Total_goal', 'Rk', 'AvAge', 'GP', 'W', 'L', 'OL', 'PTS',
       'PTS%', 'GF', 'GA', 'SOW', 'SOL', 'SRS', 'SOS', 'GF/G', 'GF/G.1', 'PP',
       'PPO', 'PP%', 'PPA', 'PPOA', 'PK%', 'SH', 'SHA', 'PIM/G', 'oPIM/G', 'S',
       'S%', 'SA', 'SV%', 'SO', 'Rk.1', 'Age', 'GP.1', 'CF', 'CA', 'CF%',
       'CF% rel', 'FF', 'FA', 'FF%', 'FF rel', 'oiSH%', 'oiSV%', 'PDO', 'oZS%',
       'dZS%', 'TK', 'GV', 'SAtt', 'Thru%', 'Rk.2', 'Age.1', 'GP.2', 'G.1.1',
       'A', 'PTS.1', '+/-', 'PIM', 'PS', 'EV', 'PP.1', 'SH.1', 'GW',
       'Assist-EV', 'PP.2', 'Assist-SH', 'S.1', 'S%.1', 'TOI', 'BLK', 'HIT',
       'FOW', 'FOL', 'FO%'],
      dtype='object')

## **`MATCHUP DATA REGULAR SEASON 2014_15 `**

In [7]:
path=r'/content/drive/MyDrive/data collection/FINAL MODEL FEEDING DATASET (V - H) direct difference/FINAL_2014_15_MODEL_FEEDING_DATASET_ATTEMPTED_BY_DIFFERENCE.csv'
data_2014_15=pd.read_csv(path)
data_2014_15.drop(["Unnamed: 0",'Visitor','Home','E+/-'],axis = 1, inplace  = True)
data_2014_15 = data_2014_15.loc[~data_2014_15.index.duplicated(keep='first')]
data_2014_15.head()
count = 0
for i in range(0,data_2014_15.shape[0]) :
    if data_2014_15.loc[i].isnull().sum() > 0 :
        count = count + 1
        print(f'Number of null values in row {i} : ' + str(data_2014_15.loc[i].isnull().sum()))
        
count
data_2014_15.columns

Index(['G', 'G.1', 'Total_goal', 'Rk', 'AvAge', 'GP', 'W', 'L', 'OL', 'PTS',
       'PTS%', 'GF', 'GA', 'SOW', 'SOL', 'SRS', 'SOS', 'GF/G', 'GF/G.1', 'PP',
       'PPO', 'PP%', 'PPA', 'PPOA', 'PK%', 'SH', 'SHA', 'PIM/G', 'oPIM/G', 'S',
       'S%', 'SA', 'SV%', 'SO', 'Rk.1', 'Age', 'GP.1', 'CF', 'CA', 'CF%',
       'CF% rel', 'FF', 'FA', 'FF%', 'FF rel', 'oiSH%', 'oiSV%', 'PDO', 'oZS%',
       'dZS%', 'TK', 'GV', 'SAtt', 'Thru%', 'Rk.2', 'Age.1', 'GP.2', 'G.1.1',
       'A', 'PTS.1', '+/-', 'PIM', 'PS', 'EV', 'PP.1', 'SH.1', 'GW',
       'Assist-EV', 'PP.2', 'Assist-SH', 'S.1', 'S%.1', 'TOI', 'BLK', 'HIT',
       'FOW', 'FOL', 'FO%'],
      dtype='object')

## **`MATCHUP DATA REGULAR SEASON 2015_16 `**

In [8]:
path=r'/content/drive/MyDrive/data collection/FINAL MODEL FEEDING DATASET (V - H) direct difference/FINAL_2015_16_MODEL_FEEDING_DATASET_ATTEMPTED_BY_DIFFERENCE.csv'
data_2015_16=pd.read_csv(path)
data_2015_16.drop(["Unnamed: 0",'Visitor','Home','E+/-'],axis = 1, inplace  = True)
data_2015_16 = data_2015_16.loc[~data_2015_16.index.duplicated(keep='first')]
data_2015_16.head()
count = 0
for i in range(0,data_2011_12.shape[0]) :
    if data_2011_12.loc[i].isnull().sum() > 0 :
        count = count + 1
        print(f'Number of null values in row {i} : ' + str(data_2011_12.loc[i].isnull().sum()))
        
count
data_2015_16.columns

Index(['G', 'G.1', 'Total_goal', 'Rk', 'AvAge', 'GP', 'W', 'L', 'OL', 'PTS',
       'PTS%', 'GF', 'GA', 'SOW', 'SOL', 'SRS', 'SOS', 'GF/G', 'GF/G.1', 'PP',
       'PPO', 'PP%', 'PPA', 'PPOA', 'PK%', 'SH', 'SHA', 'PIM/G', 'oPIM/G', 'S',
       'S%', 'SA', 'SV%', 'SO', 'Rk.1', 'Age', 'GP.1', 'CF', 'CA', 'CF%',
       'CF% rel', 'FF', 'FA', 'FF%', 'FF rel', 'oiSH%', 'oiSV%', 'PDO', 'oZS%',
       'dZS%', 'TK', 'GV', 'SAtt', 'Thru%', 'Rk.2', 'Age.1', 'GP.2', 'G.1.1',
       'A', 'PTS.1', '+/-', 'PIM', 'PS', 'EV', 'PP.1', 'SH.1', 'GW',
       'Assist-EV', 'PP.2', 'Assist-SH', 'S.1', 'S%.1', 'TOI', 'BLK', 'HIT',
       'FOW', 'FOL', 'FO%'],
      dtype='object')

## **`MATCHUP DATA REGULAR SEASON 2016_17 `**

In [9]:
path=r'/content/drive/MyDrive/data collection/FINAL MODEL FEEDING DATASET (V - H) direct difference/FINAL_2016_17_MODEL_FEEDING_DATASET_ATTEMPTED_BY_DIFFERENCE.csv'
data_2016_17=pd.read_csv(path)
data_2016_17.drop(["Unnamed: 0",'Date','Att.','Visitor','Home','E+/-'],axis = 1, inplace  = True)
data_2016_17 = data_2016_17.loc[~data_2016_17.index.duplicated(keep='first')]
data_2016_17.head()
count = 0
for i in range(0,data_2016_17.shape[0]) :
    if data_2016_17.loc[i].isnull().sum() > 0 :
        count = count + 1
        print(f'Number of null values in row {i} : ' + str(data_2016_17.loc[i].isnull().sum()))
        
count
data_2016_17.columns

Index(['Total_goal', 'Rk', 'AvAge', 'GP', 'W', 'L', 'OL', 'PTS', 'PTS%', 'GF',
       'GA', 'SOW', 'SOL', 'SRS', 'SOS', 'GF/G', 'GF/G.1', 'PP', 'PPO', 'PP%',
       'PPA', 'PPOA', 'PK%', 'SH', 'SHA', 'PIM/G', 'oPIM/G', 'S', 'S%', 'SA',
       'SV%', 'SO', 'Rk.1', 'Age', 'GP.1', 'CF', 'CA', 'CF%', 'CF% rel', 'FF',
       'FA', 'FF%', 'FF rel', 'oiSH%', 'oiSV%', 'PDO', 'oZS%', 'dZS%', 'TK',
       'GV', 'SAtt', 'Thru%', 'Rk.2', 'Age.1', 'GP.2', 'G', 'A', 'PTS.1',
       '+/-', 'PIM', 'PS', 'EV', 'PP.1', 'SH.1', 'GW', 'Assist-EV', 'PP.2',
       'Assist-SH', 'S.1', 'S%.1', 'TOI', 'BLK', 'HIT', 'FOW', 'FOL', 'FO%'],
      dtype='object')

## **`MATCHUP DATA REGULAR SEASON 2017_18 `**

In [10]:
path=r'/content/drive/MyDrive/data collection/FINAL MODEL FEEDING DATASET (V - H) direct difference/FINAL_2017_18_MODEL_FEEDING_DATASET_ATTEMPTED_BY_DIFFERENCE.csv'
data_2017_18=pd.read_csv(path)
data_2017_18.drop(["Unnamed: 0",'Visitor','Home','E+/-'],axis = 1, inplace  = True)
data_2017_18 = data_2017_18.loc[~data_2017_18.index.duplicated(keep='first')]
data_2017_18.head()
count = 0
for i in range(0,data_2011_12.shape[0]) :
    if data_2011_12.loc[i].isnull().sum() > 0 :
        count = count + 1
        print(f'Number of null values in row {i} : ' + str(data_2011_12.loc[i].isnull().sum()))
        
count
data_2017_18.columns

Index(['G', 'G.1', 'Total_goal', 'Rk', 'AvAge', 'GP', 'W', 'L', 'OL', 'PTS',
       'PTS%', 'GF', 'GA', 'SOW', 'SOL', 'SRS', 'SOS', 'GF/G', 'GF/G.1', 'PP',
       'PPO', 'PP%', 'PPA', 'PPOA', 'PK%', 'SH', 'SHA', 'PIM/G', 'oPIM/G', 'S',
       'S%', 'SA', 'SV%', 'SO', 'Rk.1', 'Age', 'GP.1', 'CF', 'CA', 'CF%',
       'CF% rel', 'FF', 'FA', 'FF%', 'FF rel', 'oiSH%', 'oiSV%', 'PDO', 'oZS%',
       'dZS%', 'TK', 'GV', 'SAtt', 'Thru%', 'Rk.2', 'Age.1', 'GP.2', 'G.1.1',
       'A', 'PTS.1', '+/-', 'PIM', 'PS', 'EV', 'PP.1', 'SH.1', 'GW',
       'Assist-EV', 'PP.2', 'Assist-SH', 'S.1', 'S%.1', 'TOI', 'BLK', 'HIT',
       'FOW', 'FOL', 'FO%'],
      dtype='object')

## **`MATCHUP DATA REGULAR SEASON 2018_19 `**

In [11]:
path=r'/content/drive/MyDrive/data collection/FINAL MODEL FEEDING DATASET (V - H) direct difference/FINAL_2018_19_MODEL_FEEDING_DATASET_ATTEMPTED_BY_DIFFERENCE_2.csv'
data_2018_19=pd.read_csv(path)
data_2018_19.drop(["Unnamed: 0",'Att.','Visitor','Home','E+/-'],axis = 1, inplace  = True)
data_2018_19 = data_2018_19.loc[~data_2018_19.index.duplicated(keep='first')]
data_2018_19.head()
count = 0
for i in range(0,data_2018_19.shape[0]) :
    if data_2018_19.loc[i].isnull().sum() > 0 :
        count = count + 1
        print(f'Number of null values in row {i} : ' + str(data_2018_19.loc[i].isnull().sum()))
        
count
data_2018_19.columns

Index(['Total_goal', 'Rk', 'AvAge', 'GP', 'W', 'L', 'OL', 'PTS', 'PTS%', 'GF',
       'GA', 'SOW', 'SOL', 'SRS', 'SOS', 'GF/G', 'GF/G.1', 'PP', 'PPO', 'PP%',
       'PPA', 'PPOA', 'PK%', 'SH', 'SHA', 'PIM/G', 'oPIM/G', 'S', 'S%', 'SA',
       'SV%', 'SO', 'Rk.1', 'Age', 'GP.1', 'CF', 'CA', 'CF%', 'CF% rel', 'FF',
       'FA', 'FF%', 'FF rel', 'oiSH%', 'oiSV%', 'PDO', 'oZS%', 'dZS%', 'TK',
       'GV', 'SAtt', 'Thru%', 'Rk.2', 'Age.1', 'GP.2', 'G', 'A', 'PTS.1',
       '+/-', 'PIM', 'PS', 'EV', 'PP.1', 'SH.1', 'GW', 'Assist-EV', 'PP.2',
       'Assist-SH', 'S.1', 'S%.1', 'TOI', 'BLK', 'HIT', 'FOW', 'FOL', 'FO%'],
      dtype='object')

## **`MATCHUP DATA REGULAR SEASON 2019_20 `**

In [12]:
path=r'/content/drive/MyDrive/data collection/FINAL MODEL FEEDING DATASET (V - H) direct difference/FINAL_2019_20_MODEL_FEEDING_DATASET_ATTEMPTED_BY_DIFFERENCE.csv'
data_2019_20=pd.read_csv(path)
data_2019_20.drop(["Unnamed: 0","Date",'Att.','Visitor','Home','E+/-'],axis = 1, inplace  = True)
data_2019_20 = data_2019_20.loc[~data_2019_20.index.duplicated(keep='first')]
data_2019_20.head()
count = 0
for i in range(0,data_2019_20.shape[0]) :
    if data_2019_20.loc[i].isnull().sum() > 0 :
        count = count + 1
        print(f'Number of null values in row {i} : ' + str(data_2019_20.loc[i].isnull().sum()))
        
count
data_2019_20.columns

Index(['Total_goal', 'Rk', 'AvAge', 'GP', 'W', 'L', 'OL', 'PTS', 'PTS%', 'GF',
       'GA', 'SOW', 'SOL', 'SRS', 'SOS', 'GF/G', 'GF/G.1', 'PP', 'PPO', 'PP%',
       'PPA', 'PPOA', 'PK%', 'SH', 'SHA', 'PIM/G', 'oPIM/G', 'S', 'S%', 'SA',
       'SV%', 'SO', 'Rk.1', 'Age', 'GP.1', 'CF', 'CA', 'CF%', 'CF% rel', 'FF',
       'FA', 'FF%', 'FF rel', 'oiSH%', 'oiSV%', 'PDO', 'oZS%', 'dZS%', 'TK',
       'GV', 'SAtt', 'Thru%', 'Rk.2', 'Age.1', 'GP.2', 'G', 'A', 'PTS.1',
       '+/-', 'PIM', 'PS', 'EV', 'PP.1', 'SH.1', 'GW', 'Assist-EV', 'PP.2',
       'Assist-SH', 'S.1', 'S%.1', 'TOI', 'BLK', 'HIT', 'FOW', 'FOL', 'FO%'],
      dtype='object')

In [13]:
path=r'/content/drive/MyDrive/data collection/FINAL MODEL FEEDING DATASET (V - H) direct difference/FINAL_2020_21_MODEL_FEEDING_DATASET_ATTEMPTED_BY_DIFFERENCE.csv'
data_2020_21=pd.read_csv(path)
data_2020_21.drop(["Unnamed: 0","Date",'Att.','Visitor','Home','E+/-'],axis = 1, inplace  = True)
data_2020_21 = data_2020_21.loc[~data_2020_21.index.duplicated(keep='first')]
data_2020_21.head()
count = 0
for i in range(0,data_2019_20.shape[0]) :
    if data_2019_20.loc[i].isnull().sum() > 0 :
        count = count + 1
        print(f'Number of null values in row {i} : ' + str(data_2019_20.loc[i].isnull().sum()))
        
count
data_2020_21.columns

Index(['Total_goal', 'Rk', 'AvAge', 'GP', 'W', 'L', 'OL', 'PTS', 'PTS%', 'GF',
       'GA', 'SOW', 'SOL', 'SRS', 'SOS', 'GF/G', 'GF/G.1', 'PP', 'PPO', 'PP%',
       'PPA', 'PPOA', 'PK%', 'SH', 'SHA', 'PIM/G', 'oPIM/G', 'S', 'S%', 'SA',
       'SV%', 'SO', 'Rk.1', 'Age', 'GP.1', 'CF', 'CA', 'CF%', 'CF% rel', 'FF',
       'FA', 'FF%', 'FF rel', 'oiSH%', 'oiSV%', 'PDO', 'oZS%', 'dZS%', 'TK',
       'GV', 'SAtt', 'Thru%', 'Rk.2', 'Age.1', 'GP.2', 'G', 'A', 'PTS.1',
       '+/-', 'PIM', 'PS', 'EV', 'PP.1', 'SH.1', 'GW', 'Assist-EV', 'PP.2',
       'Assist-SH', 'S.1', 'S%.1', 'TOI', 'BLK', 'HIT', 'FOW', 'FOL', 'FO%'],
      dtype='object')

In [14]:
final=pd.concat([data_2011_12,data_2012_13,data_2013_14,data_2014_15,data_2015_16,data_2016_17,data_2017_18,data_2018_19,data_2019_20,data_2020_21],axis=0)

In [15]:
final.isnull

<bound method DataFrame.isnull of             G  G.1  Total_goal  Rk  AvAge  GP   W   L  OL  PTS  ...      PP.2  \
0    2.000000  1.0           3  -1   -1.5   0  -2  -3   5    1  ...  1.794974
1    0.000000  2.0           2   3    0.9   0  -4  -2   6   -2  ... -0.605475
2    4.000000  3.0           7   3    0.0   0   0   3  -3   -3  ... -0.426667
3    1.000000  4.0           5   7    1.5   0  -5   4   1   -9  ...  0.578042
4    5.000000  1.0           6  -2    3.0   0   5   3  -8    2  ... -0.400000
..        ...  ...         ...  ..    ...  ..  ..  ..  ..  ...  ...       ...
863 -0.659933  NaN           6  -9    0.7   0   5  -9   4   14  ... -0.915825
864 -2.307143  NaN           5  13   -1.0   0 -12  10   2  -22  ... -1.692857
865  1.116256  NaN          11  -3    0.9   0   3  -2  -1    5  ...  0.548768
866  1.116256  NaN           6  -3    0.9   0   3  -2  -1    5  ...  0.548768
867 -1.116256  NaN           8   3   -0.9   0  -3   2   1   -5  ... -0.548768

     Assist-SH        S.1      S%.1         TOI       BLK        HIT  \
0    -0.047619  -3.103175 -4.817571  -35.051587  3.353175   6.943122
1     0.293076  -1.515298 -2.346055  -31.719807  3.454106 -11.971014
2     0.200000   2.313333 -0.314286  -66.340000 -2.526667   2.533333
3     0.042328   0.009259  2.558547   63.154762  6.104497  14.476190
4    -0.080000 -15.400000  0.340000  -96.560000 -4.000000  -5.920000
..         ...        ...       ...         ...       ...        ...
863   0.003367  -8.457912 -0.683780 -111.188552 -6.952862 -17.680135
864   0.135714 -13.207143 -0.449026 -117.707143 -5.607143 -20.342857
865  -0.102463  11.698522  1.042006   96.792118  0.344828  10.076847
866  -0.102463  11.698522  1.042006   96.792118  0.344828  10.076847
867   0.102463 -11.698522 -1.042006  -96.792118 -0.344828 -10.076847

           FOW        FOL        FO%
0   -13.376984   8.521164  -8.957602
1     2.896940  15.470209   4.487500
2    -8.940000  -0.786667   8.368750
3    12.791005  15.167989   8.593567
4   -19.640000  -9.560000  -3.888971
..         ...        ...        ...
863  -9.107744 -10.077441  -6.246324
864  -6.321429  -9.657143   4.252632
865   5.852217  10.184236 -11.300000
866   5.852217  10.184236 -11.300000
867  -5.852217 -10.184236  11.300000

[11362 rows x 78 columns]>

In [16]:
final['BLK'].isnull().any()

True

In [17]:
count = 0
for i in range(0,final.shape[0]) :
     
    if (final.loc[i]['BLK'].isnull().sum()==0) :
        count = count + 1
        print(f'Number of null values in row {i} : ' + str(final.loc[i].isnull().sum()))
        
count

Streaming output truncated to the last 5000 lines.
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 826 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 827 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 828 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 829 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 830 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 831 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 833 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 834 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 835 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 836 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 837 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 838 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 839 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 840 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 841 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 842 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 843 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 844 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 845 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 846 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 847 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 849 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 850 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 851 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 852 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 853 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 854 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 855 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 856 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 857 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 858 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 859 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 860 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 862 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 864 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 865 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 866 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 867 : G             0
G.1           4
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 868 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 869 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 870 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 871 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 872 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 873 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 874 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 875 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 876 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 877 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 878 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 879 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 880 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 881 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 882 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 883 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 884 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 885 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 887 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 888 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 889 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 890 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 891 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 892 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 893 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 894 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 895 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 896 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 897 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 898 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 899 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 901 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 902 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 903 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 904 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 905 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 906 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 907 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 908 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 909 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 910 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 911 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 912 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 913 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 914 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0
Length: 78, dtype: int64
Number of null values in row 915 : G             0
G.1           3
Total_goal    0
Rk            0
AvAge         0
             ..
BLK           0
HIT           0
FOW           0
FOL           0
FO%           0

KeyError: ignored

In [18]:
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    #df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    
    return df[indices_to_keep].astype(np.float64)

In [19]:
final=clean_dataset(final)

In [ ]:
final.shape

In [20]:
x_train=final.drop(['Total_goal','G.1','G','G.1.1',], axis =1)
#x_train=x_train.astype(float)

y_train=final['Total_goal']

In [21]:
path=r'/content/drive/MyDrive/data collection/FINAL MODEL FEEDING DATASET (V - H) direct difference/FINAL_2021_22_MODEL_FEEDING_DATASET_ATTEMPTED_BY_DIFFERENCE.csv'
data_2021_22=pd.read_csv(path)
data_2021_22.drop(["Unnamed: 0",'Visitor','Home','E+/-'],axis = 1, inplace  = True)
data_2021_22 = data_2020_21.loc[~data_2020_21.index.duplicated(keep='first')]
data_2021_22.head()
count = 0
for i in range(0,data_2021_22.shape[0]) :
    if data_2021_22.loc[i].isnull().sum() > 0 :
        count = count + 1
        print(f'Number of null values in row {i} : ' + str(data_2021_22.loc[i].isnull().sum()))
        
count

0

In [22]:
x_test=data_2020_21.drop(['Total_goal','G'], axis =1)
y_test=data_2020_21['Total_goal']

In [ ]:
x_train=x_train.astype(np.float64)

In [23]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
# y_train = y_train.to_numpy() 
# y_train.reshape(-1, 1)
#y_train = scaler.fit_transform(y_train)
x_train[0]

array([-7.98015713e-02, -1.03392365e+00,  0.00000000e+00, -1.92541145e-01,
       -3.10857795e-01,  1.18480581e+00,  5.07922640e-02,  4.76705391e-02,
        2.27677774e-04,  7.90053416e-01, -1.65981345e+00,  1.25151773e+00,
       -5.66288281e-01,  1.48654907e+00,  2.21565996e-04,  7.31524528e-01,
        2.10843745e+00,  3.11844021e+00,  6.62444076e-01,  1.32854863e+00,
        1.71880829e+00, -3.90842646e-01, -5.06428626e-01,  2.11165353e+00,
        1.17308834e+00,  2.36729513e+00, -5.59675149e-02,  1.83633859e-04,
       -5.18678766e-01, -1.28498857e+00, -5.41267658e-01,  1.92403226e+00,
       -1.28116299e-02, -2.29601251e-01, -6.73057787e-01, -2.26072845e-01,
       -3.01550457e-01,  6.68426575e-01, -6.80726529e-01, -3.94661156e-01,
       -1.03682148e-01,  7.55402003e-01,  2.20690694e-01, -6.42287515e-01,
       -2.89714092e-01, -1.98044998e-01,  1.98039208e-01, -1.21049998e-02,
        2.13132842e-01, -2.33616514e-01,  4.42234237e-01, -7.36007727e-01,
       -1.34623094e-02, -2.48009713e-01,  1.47600472e-01,  5.03176421e-02,
       -8.94001069e-01,  7.83277769e-01, -4.63630032e-01, -6.90308852e-01,
        1.77211498e+00, -6.11318567e-01,  3.06142323e-01, -5.89977052e-01,
        2.02850493e+00, -3.07854771e-01, -1.99635023e-01, -2.31190085e+00,
       -2.95890881e-01,  4.37643867e-01,  4.11354292e-01, -8.55071538e-01,
        6.56159449e-01, -1.35165097e+00])

## **LINEAR REGRESSION**

In [24]:
reg = LinearRegression()
#x_train.fillna(1)
#x_train.replace([np.inf, -np.inf], np.nan, inplace=True)
reg.fit(x_train,y_train)
r2_score = reg.score(x_test,y_test)
print(r2_score*100,'%')

-5.944835132313288e+28 %

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

### RANDOM FOREST REGRESSOR

In [25]:
from sklearn.ensemble import RandomForestRegressor
import sklearn.metrics as metrics

rf = RandomForestRegressor(n_estimators = 300, max_features = 'sqrt', max_depth = 5, random_state = 18).fit(x_train, y_train)
rf.fit(x_train, y_train) 
y_pred = rf.predict(x_test)
rmse = metrics.mean_squared_error(y_test,y_pred)
rmse

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

5.353798317754215

## **SUPPORT VECTOR CLASSIFIER**

In [27]:
from sklearn.svm import SVC 
clf = SVC(kernel='linear')
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
pred = clf.predict(x_test)
metrics.accuracy_score(y_test,y_pred=pred)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but SVC was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but SVC was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

0.18548387096774194

**DECISION TREE REGRESSOR**

In [30]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)
score =regressor.score(x_train, y_train)
print("R-squared:", score)

R-squared: 0.6600004063564884

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but DecisionTreeRegressor was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"